name: Sync with Forked Repo
on:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sync with Forked Repo
        run: |
          git remote add upstream https://github.com/trickest/cve.git
          git fetch upstream
          git checkout master
          git merge upstream/master --no-edit
          git push origin master
